image: nixos/nix:latest

variables:
  NIX_PATH: "nixpkgs=channel:nixos-unstable"

stages:
  - test

Run tests:
  stage: test
  script:
    - nix --experimental-features "nix-command flakes" flake check
